let ropevim_enable_shortcuts = 0
let g:pymode_rope_goto_def_newwin = "vnew"
let g:pymode_rope_extended_complete = 0
let g:pymode_breakpoint = 0
let g:pymode_syntax = 1
let g:pymode_folding = 1
let g:pymode_run = 0
let g:pymode_lint_checkers = ['pyflakes', 'mccabe']
let g:pymode_rope = 0
